### ISSUE TITLE
Support GIF captcha

### ISSUE THREAD

**Issue by ShreyashKira** [ShreyashKira/captcha-canvas#1]
Provide support for GIF captcha which is harder to detect.

**Comment by ShreyashKira** [comment]
There's no point to do that robots can easily get a single frame and retrace captcha from there so...

**Comment by Shashank3736** [comment]
This issue may become a feature in any future update

**Comment by Shashank3736** [comment]
@all-contributors please add @Shashank3736 For complete development of this awesome package.

**Comment by Shashank3736** [comment]
@all-contributors please add @Shashank3736 for this awesome package ✨

**Comment by Shashank3736** [comment]
@all-contributors please add @IchiiDev for reporting and solving debug error

**Comment by Shashank3736** [comment]
@all-contributors please add @Shashank3736 for Project management
